FROM python:3.12-slim

WORKDIR /backend



RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

COPY . .

RUN uv sync 

EXPOSE 8000

CMD [ "uv" , "run" , "uvicorn" ,"main:app" , "--reload" ]